spring.application.name=cadastroLivros
spring.datasource.url=jdbc:postgresql://localhost:5432/ProjetoLivros
spring.datasource.username=postgres
spring.datasource.password=Mc200680

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driverClassName=org.postgresql.Driver
